DROP TABLE IF EXISTS fact_building;

CREATE TABLE fact_building AS 

SELECT 
        CAST(EGID AS INTEGER)           AS	federal_building_identifier,
        GDEKT                           AS	canton_abbreviation,
        CAST(GGDENR AS INTEGER)         AS	municipality_ust_number,
        GGDENAME                        AS	municipality_name,
        EGRID                           AS	federal_fund_identifier,
        CAST(LGBKR AS INTEGER)          AS	land_register_section_number,
        CAST(LPARZ AS INTEGER)          AS	particle_number,
        LPARZSX                         AS	fund_number_suffix,
        NULLIF(CAST(LTYP AS INTEGER), 0) AS	fund_type_code,
        CAST(GEBNR AS INTEGER)          AS	building_official_number,
        GBEZ                            AS	building_name,
        GKODE                           AS	building_e_coordinate,
        GKODN                           AS	building_n_coordinate,
        CAST(GKSCE AS INTEGER)          AS	coordinates_origin_code,
        CAST(GSTAT AS INTEGER)          AS	building_state_code,
        CAST(GKAT AS INTEGER)           AS	building_category_code,
        NULLIF(CAST(GKLAS AS INTEGER), 0)       AS	building_class_code,
        CAST(GBAUJ AS INTEGER)          AS	building_construction_year,
        CAST(GBAUM AS INTEGER)          AS	building_construction_month,
        NULLIF(CAST(GBAUP AS INTEGER), 0)          AS	construction_period_code,
        CAST(GABBJ AS INTEGER)          AS	building_demolition_year,
        CAST(GAREA AS INTEGER)          AS	building_surface,
        CAST(GVOL AS INTEGER)           AS	building_volume,
        NULLIF(CAST(GVOLNORM AS INTEGER), 0)       AS	building_volume_standard_code,
        NULLIF(CAST(GVOLSCE AS INTEGER), 0)        AS	building_volume_data_indication_code,
        CAST(GASTW AS INTEGER)          AS	floors_number,
        CAST(GANZWHG AS INTEGER)        AS	homes_number,
        CAST(GAZZI AS INTEGER)          AS	rooms_number,
        CAST(GSCHUTZR AS INTEGER)       AS	civil_protection_shelter_code,
        CAST(GEBF AS INTEGER)           AS	energy_reference_surface,
        NULLIF(CAST(GWAERZH1 AS INTEGER), 0)       AS	heating_generator_1_code,
        NULLIF(CAST(GENH1 AS INTEGER), 0)          AS	heating_energy_source_1_code,
        NULLIF(CAST(GWAERSCEH1 AS INTEGER), 0)     AS	heating_information_source_1_code,
        GWAERDATH1                      AS	heating_date_update_1,
        NULLIF(CAST(GWAERZH2 AS INTEGER), 0)       AS	heating_generator_2_code,
        NULLIF(CAST(GENH2 AS INTEGER), 0)          AS	heating_energy_source_2_code,
        NULLIF(CAST(GWAERSCEH2 AS INTEGER), 0)     AS	heating_information_source_2_code,
        GWAERDATH2                      AS	heating_date_update_2,
        NULLIF(CAST(GWAERZW1 AS INTEGER), 0)       AS	hot_water_heat_generator_1_code,
        NULLIF(CAST(GENW1 AS INTEGER), 0)          AS	hot_water_heat_source_1_code,
        NULLIF(CAST(GWAERSCEW1 AS INTEGER), 0)     AS	hot_water_information_source_1_code,
        GWAERDATW1                      AS	hot_water_update_date_1,
        NULLIF(CAST(GWAERZW2 AS INTEGER), 0)       AS	hot_water_heat_generator_2_code,
        NULLIF(CAST(GENW2 AS INTEGER), 0)          AS	hot_water_heat_source_2_code,
        NULLIF(CAST(GWAERSCEW2 AS INTEGER), 0)     AS	hot_water_information_source_2_code,
        GWAERDATW2                      AS	hot_water_update_date_2,
        GEXPDAT                         AS	export_date
FROM    building;